# -*- coding: utf-8 -*-
"""pscan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sLwadsSCTY2iGRKSPs2Vu5PEKO6C8DZD
"""

import socket

ip = input("Digite host ou Ip a ser Verificado: ")

ports = []
count = 0

while count <10:
  ports.append(int(input("Digite a Porta a ser Verificada: ")))
  count +=1

for port in ports:
  client =socket.socket(socket.AF_INET,socket.SOCK_STREAM)
  client.settimeout(0.05)
  code = client.connect_ex((ip, port))

if code == 0:
   print(str(port),"-->Porta Aberta")
else:
   print(str(port),"-->Porta Fechada")

print(" Scan Finalizado")

